//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace BindSchedulerToEF
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CarsDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CarsDBEntities object using the connection string found in the 'CarsDBEntities' section of the application configuration file.
        /// </summary>
        public CarsDBEntities() : base("name=CarsDBEntities", "CarsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CarsDBEntities object.
        /// </summary>
        public CarsDBEntities(string connectionString) : base(connectionString, "CarsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CarsDBEntities object.
        /// </summary>
        public CarsDBEntities(EntityConnection connection) : base(connection, "CarsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Car> Cars
        {
            get
            {
                if ((_Cars == null))
                {
                    _Cars = base.CreateObjectSet<Car>("Cars");
                }
                return _Cars;
            }
        }
        private ObjectSet<Car> _Cars;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CarScheduling> CarSchedulings
        {
            get
            {
                if ((_CarSchedulings == null))
                {
                    _CarSchedulings = base.CreateObjectSet<CarScheduling>("CarSchedulings");
                }
                return _CarSchedulings;
            }
        }
        private ObjectSet<CarScheduling> _CarSchedulings;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cars EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCars(Car car)
        {
            base.AddObject("Cars", car);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CarSchedulings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCarSchedulings(CarScheduling carScheduling)
        {
            base.AddObject("CarSchedulings", carScheduling);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CarsDBModel", Name="Car")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Car : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Car object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Car CreateCar(global::System.Int32 id)
        {
            Car car = new Car();
            car.ID = id;
            return car;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Trademark
        {
            get
            {
                return _Trademark;
            }
            set
            {
                OnTrademarkChanging(value);
                ReportPropertyChanging("Trademark");
                _Trademark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Trademark");
                OnTrademarkChanged();
            }
        }
        private global::System.String _Trademark;
        partial void OnTrademarkChanging(global::System.String value);
        partial void OnTrademarkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Model
        {
            get
            {
                return _Model;
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.String _Model;
        partial void OnModelChanging(global::System.String value);
        partial void OnModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> HP
        {
            get
            {
                return _HP;
            }
            set
            {
                OnHPChanging(value);
                ReportPropertyChanging("HP");
                _HP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HP");
                OnHPChanged();
            }
        }
        private Nullable<global::System.Int16> _HP;
        partial void OnHPChanging(Nullable<global::System.Int16> value);
        partial void OnHPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Liter
        {
            get
            {
                return _Liter;
            }
            set
            {
                OnLiterChanging(value);
                ReportPropertyChanging("Liter");
                _Liter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Liter");
                OnLiterChanged();
            }
        }
        private Nullable<global::System.Double> _Liter;
        partial void OnLiterChanging(Nullable<global::System.Double> value);
        partial void OnLiterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> Cyl
        {
            get
            {
                return _Cyl;
            }
            set
            {
                OnCylChanging(value);
                ReportPropertyChanging("Cyl");
                _Cyl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cyl");
                OnCylChanged();
            }
        }
        private Nullable<global::System.Byte> _Cyl;
        partial void OnCylChanging(Nullable<global::System.Byte> value);
        partial void OnCylChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> TransmissSpeedCount
        {
            get
            {
                return _TransmissSpeedCount;
            }
            set
            {
                OnTransmissSpeedCountChanging(value);
                ReportPropertyChanging("TransmissSpeedCount");
                _TransmissSpeedCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransmissSpeedCount");
                OnTransmissSpeedCountChanged();
            }
        }
        private Nullable<global::System.Byte> _TransmissSpeedCount;
        partial void OnTransmissSpeedCountChanging(Nullable<global::System.Byte> value);
        partial void OnTransmissSpeedCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TransmissAutomatic
        {
            get
            {
                return _TransmissAutomatic;
            }
            set
            {
                OnTransmissAutomaticChanging(value);
                ReportPropertyChanging("TransmissAutomatic");
                _TransmissAutomatic = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TransmissAutomatic");
                OnTransmissAutomaticChanged();
            }
        }
        private global::System.String _TransmissAutomatic;
        partial void OnTransmissAutomaticChanging(global::System.String value);
        partial void OnTransmissAutomaticChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> MPG_City
        {
            get
            {
                return _MPG_City;
            }
            set
            {
                OnMPG_CityChanging(value);
                ReportPropertyChanging("MPG_City");
                _MPG_City = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MPG_City");
                OnMPG_CityChanged();
            }
        }
        private Nullable<global::System.Byte> _MPG_City;
        partial void OnMPG_CityChanging(Nullable<global::System.Byte> value);
        partial void OnMPG_CityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> MPG_Highway
        {
            get
            {
                return _MPG_Highway;
            }
            set
            {
                OnMPG_HighwayChanging(value);
                ReportPropertyChanging("MPG_Highway");
                _MPG_Highway = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MPG_Highway");
                OnMPG_HighwayChanged();
            }
        }
        private Nullable<global::System.Byte> _MPG_Highway;
        partial void OnMPG_HighwayChanging(Nullable<global::System.Byte> value);
        partial void OnMPG_HighwayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Hyperlink
        {
            get
            {
                return _Hyperlink;
            }
            set
            {
                OnHyperlinkChanging(value);
                ReportPropertyChanging("Hyperlink");
                _Hyperlink = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Hyperlink");
                OnHyperlinkChanged();
            }
        }
        private global::System.String _Hyperlink;
        partial void OnHyperlinkChanging(global::System.String value);
        partial void OnHyperlinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Picture
        {
            get
            {
                return StructuralObject.GetValidValue(_Picture);
            }
            set
            {
                OnPictureChanging(value);
                ReportPropertyChanging("Picture");
                _Picture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Picture");
                OnPictureChanged();
            }
        }
        private global::System.Byte[] _Picture;
        partial void OnPictureChanging(global::System.Byte[] value);
        partial void OnPictureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Price;
        partial void OnPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RtfContent
        {
            get
            {
                return _RtfContent;
            }
            set
            {
                OnRtfContentChanging(value);
                ReportPropertyChanging("RtfContent");
                _RtfContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RtfContent");
                OnRtfContentChanged();
            }
        }
        private global::System.String _RtfContent;
        partial void OnRtfContentChanging(global::System.String value);
        partial void OnRtfContentChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CarsDBModel", Name="CarScheduling")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CarScheduling : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CarScheduling object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="allDay">Initial value of the AllDay property.</param>
        public static CarScheduling CreateCarScheduling(global::System.Int32 id, global::System.Boolean allDay)
        {
            CarScheduling carScheduling = new CarScheduling();
            carScheduling.ID = id;
            carScheduling.AllDay = allDay;
            return carScheduling;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CarId
        {
            get
            {
                return _CarId;
            }
            set
            {
                OnCarIdChanging(value);
                ReportPropertyChanging("CarId");
                _CarId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CarId");
                OnCarIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CarId;
        partial void OnCarIdChanging(Nullable<global::System.Int32> value);
        partial void OnCarIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Status;
        partial void OnStatusChanging(Nullable<global::System.Int32> value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Label
        {
            get
            {
                return _Label;
            }
            set
            {
                OnLabelChanging(value);
                ReportPropertyChanging("Label");
                _Label = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Label");
                OnLabelChanged();
            }
        }
        private Nullable<global::System.Int32> _Label;
        partial void OnLabelChanging(Nullable<global::System.Int32> value);
        partial void OnLabelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartTime;
        partial void OnStartTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndTime;
        partial void OnEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean AllDay
        {
            get
            {
                return _AllDay;
            }
            set
            {
                OnAllDayChanging(value);
                ReportPropertyChanging("AllDay");
                _AllDay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllDay");
                OnAllDayChanged();
            }
        }
        private global::System.Boolean _AllDay;
        partial void OnAllDayChanging(global::System.Boolean value);
        partial void OnAllDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EventType
        {
            get
            {
                return _EventType;
            }
            set
            {
                OnEventTypeChanging(value);
                ReportPropertyChanging("EventType");
                _EventType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventType");
                OnEventTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _EventType;
        partial void OnEventTypeChanging(Nullable<global::System.Int32> value);
        partial void OnEventTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RecurrenceInfo
        {
            get
            {
                return _RecurrenceInfo;
            }
            set
            {
                OnRecurrenceInfoChanging(value);
                ReportPropertyChanging("RecurrenceInfo");
                _RecurrenceInfo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RecurrenceInfo");
                OnRecurrenceInfoChanged();
            }
        }
        private global::System.String _RecurrenceInfo;
        partial void OnRecurrenceInfoChanging(global::System.String value);
        partial void OnRecurrenceInfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReminderInfo
        {
            get
            {
                return _ReminderInfo;
            }
            set
            {
                OnReminderInfoChanging(value);
                ReportPropertyChanging("ReminderInfo");
                _ReminderInfo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReminderInfo");
                OnReminderInfoChanged();
            }
        }
        private global::System.String _ReminderInfo;
        partial void OnReminderInfoChanging(global::System.String value);
        partial void OnReminderInfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Price;
        partial void OnPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactInfo
        {
            get
            {
                return _ContactInfo;
            }
            set
            {
                OnContactInfoChanging(value);
                ReportPropertyChanging("ContactInfo");
                _ContactInfo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactInfo");
                OnContactInfoChanged();
            }
        }
        private global::System.String _ContactInfo;
        partial void OnContactInfoChanging(global::System.String value);
        partial void OnContactInfoChanged();

        #endregion

    
    }

    #endregion

    
}
